apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-server
  name: app-svc
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: app-server
status:
  loadBalancer: {}
