apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb/
